### PR TITLE
Simplify beaneater

### PR DESCRIPTION
**Pull request by alup**
This is a WIP. @nesquena what do you think so far?

### CODE REVIEW

**Comment by nesquena** [comment]
I'm really liking this! Just make sure tests pass and also (harder part) update the README accordingly and when ready we will push this out as a major release. Looks like it will break the API? so we need to update https://github.com/nesquena/backburner as well (good test of consuming this library)

**Comment by alup** [comment]
@nesquena Thanks for your time, I have added some more fixes. Now, tests are passing. I have to update the README in the next days and maybe add some more tests to cover all the major cases.

I have also some more enhancements in mind, we could implement in the next iterations.

**Comment by alup** [comment]
@nesquena Hello, I have updated documentation and added a new branch for Backburner -> https://github.com/alup/backburner/tree/support_new_beaneater_version

**Comment by nesquena** [comment]
Merged after I reviewed and did a little cleanup. Thanks!

**Comment by alup** [comment]
:clap:

**Pull request merged**
